language: node_js
node_js: stable
addons:
  chrome: stable
install:
- npm ci
- npm i --no-save @api-components/api-model-generator
script:
- npm run test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: NaS9w6KYU7i27ydDadnd1ZFinxZDz/W6Kr2r3gDvfhW98cAbAjUnQ23yzKy2BHtqPiQNLNR+dCdeO/ZtUIB0bSF6bCqBxHMQKTgPGdUgXC08csClc0Ck/9Y22yTsUCMiZwMholhyMKYBNLXUszTA78br8/Z1tQ3fiW80evfJM4MlYRMvs02NjDSHFPlCokafpLmtVYA5ZnuMBKDVpfEvVapXDEXJY8/F0UqLqCoOEyKmhvuDPD2Spw0dbj/LBZnwJHN+tr6ZL0gQjMWy94qdtRhbOR7vKuqCjqhAFe7tZx7XEIteNJexOtC0z55cxnNXXoRxdJza28XdSVPWxW1lIy+0KChkMF3VLDvSCNftQWIvzID4jIToXO2WzVu9/74D4ujmn2Nx5JQy2jo3nprVSd/EXtgceYDx2Pv6eFqFnDtcl/rikxPFHQsbdqhRXHaQG+jDbQeqgNNZawH4zjaVqqYr+tg88fhft0Ab6gr4taYVRv7kWp4dZfzazvvWJ5tXehMy/knX9B35drCG3coNX4TbeIINtFy+WCULiAGvH77S4MdWhth/7dh5LRPk/XWfIDlXm3vrw/mmt93ylSDq2JAmf2pX6Yiv557ietVl+yO9o0qiPC0jApRZK6jKkQutbm0h3MRBZAfbY3nQT6ul4DmdGnrTjQrAAWmvx6+wi80=
  - secure: aRWHcUC6kVV5bkdp4k0EzT9jmdyqgoMaB24DQaBgSLOORAfXdU+6GN4mg4qDfYZhPqRUOPpmOYo313MNyn9g3qePzp8y5XfQ+Bcs/ljgZCTsbUlLJ7Vf+3pedq09HsWnJOMwukZFMAR3/hH/aDRoJkcKtQeWuhR5PJOUK4Kiq2ngIG88ZCebqcReIt+yRCxm3HRzko+P4CDJ0OUiWJAXuq82LpuV2djNF0ckxWK2HT3HUu+/7vaBCZMOTxfC8JttdRZmmJReCOsHITS3WpAcnd/VU2MMKdg7M7VxiUeWXofmY2LOdedsZZh/eXFx0vBEB6JNsizVHaZPWrJK744pExRQZbkim2jBzlRlYXs2/Efa16eCfAH9VmljzEqxv5kKbSbyR64/V6WoYJPLgnkXP1yq5wlZuJNlSWJLneTth54YNQdrcaOKgcJbkt5Xa2qj8d2xtqiVdYoGllAZ6U1xowmZdxalk0tGQEE5wH5pdpeR+iha5xmUy3CtqDNKqCfKNYGZT2L3vIaQnP90Jm/f68C6Qlty9TDnRsZUBdul9qAxpZvW5cRocNdqKwX6XYOQB/Arbu0iKmV/J79eQBrZdQSETl2yJ200uR9ATCWZbeq6wq/sYNVWlML39eyU3jl9fTrBwLDQ0trHNMpsomQDGfAMqDL91iGkCGEguFfWDWQ=
